version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: fast_tag
      POSTGRES_USER: fast_tag_user
      POSTGRES_PASSWORD: fast_tag_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fast_tag_user -d fast_tag"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: