version: '3.8'

services:
  postgres-test:
    image: postgres:15
    environment:
      POSTGRES_DB: fast_tag_test
      POSTGRES_USER: fast_tag_test_user
      POSTGRES_PASSWORD: fast_tag_test_password
    ports:
      - "5433:5432"  # Different port to avoid conflict with dev
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fast_tag_test_user -d fast_tag_test"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio-test:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9002:9000"   # MinIO API - different port
      - "9003:9001"   # MinIO Console - different port
    volumes:
      - minio_test_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  postgres_test_data:
  minio_test_data: